name: Android CI with Fastlane

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 17

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name: Build AccelerometerTouchTrackerSdk
      run: ./gradlew :AccelerometerTouchTrackerSdk:build

    - name: Run unit tests
      run: ./gradlew :AccelerometerTouchTrackerSdk:test

    - name: Run Android Lint
      run: ./gradlew :AccelerometerTouchTrackerSdk:lint

    - name: Run ktlint
      run: ./gradlew :AccelerometerTouchTrackerSdk:ktlintCheck

    - name: Run detekt
      run: ./gradlew :AccelerometerTouchTrackerSdk:detekt

    - name: Konsist consistency check
      run: ./gradlew konsistCheck

    - name: Generate Dokka documentation
      run: ./gradlew :AccelerometerTouchTrackerSdk:dokkaHtml


  bump-version:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1

      - name: Install Fastlane
        run: gem install fastlane

      - name: Bump version with Fastlane
        run: fastlane bump_version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
